export const GET_PRODUCTS_BY_USER_ID_QUERY = `
    id,
    asin,
    url,
    image,
    title,
    price->>'amount' AS amount,
    price->>'currency' AS currency,
    price->>'displayAmount' AS displayAmount,
    price->>'originalPrice' AS originalPrice,
    price->>'priceHistory' AS priceHistory,
    price->>'savings' AS savings,
    category,
    number_of_comments AS numberOfComments,
    average_rating AS averageRating,
    is_out_of_stock AS isOutOfStock,
    brand,
    retailer,
    best_seller_ranks AS bestSellerRanks,
    is_amazon_choice AS isAmazonChoice,
    is_best_seller AS isBestSeller,
    histogram,
    delivery_location AS deliveryLocation,
    sales_volume_last_month AS salesVolumeLastMonth,
    average_sentiment_analysis AS averageSentimentAnalysis,
    business_target_for_collecting AS businessTargetForCollecting,
    created_at AS createdAt,
    updated_at AS updatedAt,
    user_products!inner(user_id)
` as const;